port: ::KIBANA_PORT::
host: "::KIBANA_HOST::"
elasticsearch_url: "http://::ES_HOST:::::ES_PORT::"
elasticsearch_preserve_host: true
kibana_index: "::KIBANA_INDEX::"
default_app_id: "::APP_ID::"
request_timeout: ::REQUEST_TIMEOUT::
shard_timeout: ::SHARD_TIMEOUT::
verify_ssl: ::VERIFY_SSL::
bundledPluginIds:
 - plugins/dashboard/index
 - plugins/discover/index
 - plugins/settings/index
 - plugins/table_vis/index
 - plugins/vis_types/index
 - plugins/visualize/index
